### ISSUE TITLE
Missing comma after line 152

### ISSUE THREAD

**Issue by DeepYogurt** [Piker-Alpha/HandyScripts#10]
Line 152 of the smcver.py program seems to be missing a comma at the end of the line - prevents the program from running.

**Comment by Piker-Alpha** [comment]
Thank you for reporting this issue here.

Closing issue as resolved with commit [093f712](https://github.com/Piker-Alpha/HandyScripts/commit/093f71250d25003a0acc464dfe98f266df869727).
