### ISSUE TITLE
[installSeed.py] No module named Foundation

### ISSUE THREAD

**Issue by shatteringlass** [Piker-Alpha/HandyScripts#6]
I tried installing [`foundation`](https://pypi.python.org/pypi/foundation) and [`foundations`](https://pypi.python.org/pypi/foundations) and neither provide `NSLocale`. What's the issue?

```python
Traceback (most recent call last):
  File "installSeed.py", line 58, in <module>
    from Foundation import NSLocale
ImportError: No module named Foundation
```

**Comment by Piker-Alpha** [comment]
It's "Foundation" with a capital, and I haven't installed any modules after two fresh installations of Sierra and High Sierra. Which is what I use for testing, so this is kind of new to me.

I added a -v to the first line of the script and got this:

import Foundation # directory /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Foundation

Looks like it is part of PyObjC Oops.

**Comment by shatteringlass** [comment]
Then it's probably because I'm using python from homebrew instead of the
native one.

Il 29 set 2017 8:52 PM, "Pike R. Alpha" <notifications@github.com> ha
scritto:

**Comment by Piker-Alpha** [comment]
Then I think that you need to [install PyObjC](http://pythonhosted.org/pyobjc/install.html)

**Comment by shatteringlass** [comment]
Tried installing pyobjc with no success. Maybe the module has to be imported differently. Anyway, I ended up running the script with `/usr/bin/python` and everything's good. I'm closing the issue, I guess.
