### ISSUE TITLE
efiver.py Doesn't highlight my machine

### ISSUE THREAD

**Issue by greyhound3** [Piker-Alpha/HandyScripts#7]
Thanks for this gem, but I don't know if the error is on my side.
I think this is my problem, the showSystemData never gets executed (Version is 2.0 of efiver.py).
![grafik](https://user-images.githubusercontent.com/10048796/31306961-38fd34f0-ab5b-11e7-943a-580b1fa83254.png)

One question about the line 258, is the ";" after break necessary?

**Comment by Piker-Alpha** [comment]
Hi,

Ah yes. That's a stupid error. Need to convert the data object to a string and then strip the trailing NULL byte. Should be fine in v2.1 Please give it a try. 

The semicolon is a bad habit. A C programmers thing. Removed. Thanks!

Thank you for reporting this issue here!

**Comment by greyhound3** [comment]
Hi, thanks a lot, highlighting works now!!
But for information: to run the v2.2 script now it is necessary to run it with sudo, just entering the password like before doesn't work anymore. I don't know if this is intended. 
But now it works!
Thanks for your work!!

without sudo it gives just this (even after deleting the /tmp/InstallAss.... dir) :
Traceback (most recent call last):
  File "./efiver.py", line 562, in <module>
    main()
  File "./efiver.py", line 503, in main
    if extractPayloadToDirectory() == True:
  File "./efiver.py", line 458, in extractPayloadToDirectory
    if not convertPayloadToZX(payloadPath):
  File "./efiver.py", line 433, in convertPayloadToZX
    with open(payloadPath, 'rb') as sourceFile:
IOError: [Errno 13] Permission denied: '/tmp/InstallAssistantAuto/Payload'

But for me it's not a problem.

**Comment by Piker-Alpha** [comment]
Hi,

The next update of installSeed.py runs pkgutil without sudo. For now. Remove it from this line:
```
subprocess.call(["sudo", "pkgutil", "--expand", targetFilename, unpackPackage])
```
